# Generated by Django 5.1.7 on 2025-03-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruits", "Fruits"),
                            ("vegetables", "Vegetables"),
                            ("seeds", "Seeds"),
                            ("tools", "Tools"),
                            ("fertilizers", "Fertilizers"),
                            ("pesticides", "Pesticides"),
                            ("machinery", "Machinery"),
                            ("irrigation", "Irrigation Equipment"),
                            ("packaging", "Packaging Materials"),
                            ("feed", "Animal Feed"),
                            ("medicine", "Veterinary Medicine"),
                            ("compost", "Compost & Soil"),
                            ("greenhouse", "Greenhouse Supplies"),
                            ("safety", "Safety Equipment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
