import type { Metadata } from "next";
import "./globals.css";
import Scroll from "@/components/Scroll";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'basefont-medium antialiased bg-black'}>
        <Scroll>
          <Toaster richColors/>
          <div className="flex-col">
            {children}
          </div>
        </Scroll>
      </body>
    </html>
  );
}
